all: graphdriver

graphdriver:vertex.cpp vertex.hpp graph.cpp graph.hpp graphdriver.cpp illegal_exception.hpp illegal_exception.cpp
	g++ graphdriver.cpp graph.cpp vertex.cpp illegal_exception.cpp

clean: rm graphdriver
