all: graphdriver

graphdriver:vertex.cpp vertex.hpp adjacentList.hpp adjacentList.cpp graph.cpp graph.hpp graphdriver.cpp illegal_exception.hpp illegal_exception.cpp
	g++ graphdriver.cpp graph.cpp vertex.cpp adjacentList.cpp illegal_exception.cpp

clean: rm graphdriver
